FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY cmd/web/static /static
COPY bin/web /
COPY scripts/web.sh /run.sh
ENV VCAP_SERVICES '{"postgres": [{"credentials": {"username": "dratpg", "host": "dratpg", "password": "dratpg", "name": "dratpg", "port": 5432}, "tags": ["postgres"]}]}'
ENV VCAP_APPLICATION '{}'
ENTRYPOINT ["/run.sh"]
